<?php
namespace ws\komerci\enum;

use ws\komerci\enum\EnumAbstract;

class CommonErrorsEnum extends EnumAbstract {
	const PARAMETRO_OBRIGATORIO = '20';
	const FILIACAO_FORMATO_INCORRETO = '21';
	const PARCELAS_TRANSACAO_NUM_IMCOMPATIVEL = '22';
	const ESTABELECIMENTO_PROBLEMAS_CADASTRO = '23';
	const ESTABELECIMENTO_PROBLEMAS_CADASTRO24 = '23';
	const TRANSACAO_FORMATO_INCORRETO = '25';
	const TRANSACAO_FORMATO_INCORRETO26 = '26';
	const CARTAO_INVALIDO = '27';
	const CVC_2_FORMATO_INCORRETO = '28';
	const IATA_FORMATO_INCORRETO = '29';
	const AVS_VAZIO = '30';
	const PEDIDO_FORMATO_INCORRETO = '31';
	const IATA_VAZIO = '32';
	const IATA_INVALIDO = '33';
	const DISTRIBUIDOR_INVALIDO = '34';
	const ESTABELECIMENTO_PROBLEMAS_CADASTRO35 = '35';
	const OPERACAO_NAO_PERMITIDA = '36';
	const DISTRIBUIDOR_INVALIDO37 = '37';
	const TESTE_OPERACAO_NAO_PERMITIDA = '38';
	const IATA_OPERACAO_NAO_PERMITIDA = '39';
	const IATA_VAZIO40 = '40';
	const ESTABELECIMENTO_PROBLEMAS_CADASTRO41 = '41';
	const USUARIO_ESTABELECIMENTO_PROBLEMAS_CADASTRO = '42';
	const USUARIO_INVALIDO = '43';
	const TESTE_USUARIO_INVALIDO = '44';
	const TESTE_ESTABELECIMENTO_CADASTRO = '45';
	const DADOS_INVALIDOS = '56';
}